name: Wing Chun System
favicon: null
layout_spectrum: 0.4354921
typography_spectrum: 0.1935484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9199795
  lightness: 0.5938966
  saturation: 0.3459857
  rhythmicContrast: 0.6075965
purpose: []
